name: ci
on: push

jobs:
    test:
        name: Test
        runs-on: ubuntu-22.04
        steps:
          - uses: dtolnay/rust-toolchain@stable
          - uses: actions/checkout@v4
          - run: cargo test
